### PR TITLE
Quick fix sl baseurl + Fix problem in FF

### LINKED ISSUE #477: Compatibility Issues with plone 4.3.17 and greater.
Plone 4.3.17 introduced the base-url body attribute. 
Which behaves differently from the `<base>` tag. 
Simplelayout should get rid of that

### PR DESCRIPTION
**Pull request by maethu**
This implements falling back on the base tag if there is one. 
This will work until plone 5, plone 5 no longer has a base-tag. This issue will be fixed within the plone 5.1.x branch (good solution)

PLUS:
Add missing event parameter. --> Fixes FF

Resolves #477

### CODE REVIEW

File: ftw/simplelayout/browser/resources/main.js [hunk 1]
```diff
@@ -70,7 +70,7 @@
 
     var target = $("body");
 
-    var baseUrl = $("body").data("base-url") ? $("body").data("base-url") + "/" : $("base").attr("href");
+    var baseUrl = $("body").data("base-url") && $("base").length === 0 ? $("body").data("base-url") + "/" : $("base").attr("href");
```
Comment (jone) [inline ftw/simplelayout/browser/resources/main.js]: @maethu If I understand that correctly you are reverting the priority here. I think you could revert the condition and it would be easier understandable:
from: a && !b ? a : b
to:  b ?  b : a
Isn't that the same / does what you want?

Comment (maethu) [reply ftw/simplelayout/browser/resources/main.js]: yep ;-) and done

**Comment by maethu** [comment]
I'll go for it, thanks for the hint!
